name: tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  unit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test -- --coverage
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run lint
